### ISSUE TITLE
IDA 7.0

### ISSUE THREAD

**Issue by vanhauser-thc** [alessandrogario/IDA-Function-Tagger#2]
How about support for IDA 7.0 ?
Sadly it does not work on the new version anymore.
:)

**Comment by alessandrogario** [comment]
Sorry for the super late reply; have you tried with IDA 7.1? It should work fine now.

**Comment by vanhauser-thc** [comment]
just tried with 7.1 - the list is still empty ... (example is from ida64 on Windows with the Linux x64 binary unrar)
![capture](https://user-images.githubusercontent.com/7396244/37263394-3d8e4870-25a8-11e8-971d-9dca634573aa.JPG)

**Comment by alessandrogario** [comment]
Hey @vanhauser-thc! You need to click the "Scan database" button on the bottom right and then select a .cfg profile. The only issue is that there is only one profile for Windows, and you have opened a linux binary; you should try with a Windows PE

**Comment by vanhauser-thc** [comment]
OK may bad ...

I  kinda thought your script would work differently: checking which imports are called in a function and then renaming the function to that.

You are going down the more complicated road, renaming based on grouping which you have to do first manually in a json file.

In my projects the binaries are using individual libraries so that approach would be useless as I could not reuse the databases ...

too bad! 
And I should have checked first how your script really works instead of assuming ;) sorry!
